name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs at midnight
  workflow_dispatch: # Allows manual trigger
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dhodgson615
          template: classic
          base: header, community, repositories, metadata
          config_timezone: America/New_York
          filename: github-metrics.svg
          optimize: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 20
          plugin_languages_threshold: 0%
